/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nfs3exp_prot.h"
#include "nfs3_prot.h"

bool_t
xdr_ex_fattr3(XDR *xdrs, ex_fattr3 *objp)
{

	 register int32_t *buf;

	 if (!xdr_ftype3(xdrs, &objp->type)) {
		 return (FALSE);
	 }
	 if (!xdr_uint32(xdrs, &objp->mode)) {
		 return (FALSE);
	 }
	 if (!xdr_uint32(xdrs, &objp->nlink)) {
		 return (FALSE);
	 }
	 if (!xdr_uint32(xdrs, &objp->uid)) {
		 return (FALSE);
	 }
	 if (!xdr_uint32(xdrs, &objp->gid)) {
		 return (FALSE);
	 }
	 if (!xdr_uint64(xdrs, &objp->size)) {
		 return (FALSE);
	 }
	 if (!xdr_uint64(xdrs, &objp->used)) {
		 return (FALSE);
	 }
	 if (!xdr_specdata3(xdrs, &objp->rdev)) {
		 return (FALSE);
	 }
	 if (!xdr_uint64(xdrs, &objp->fsid)) {
		 return (FALSE);
	 }
	 if (!xdr_uint64(xdrs, &objp->fileid)) {
		 return (FALSE);
	 }
	 if (!xdr_nfstime3(xdrs, &objp->atime)) {
		 return (FALSE);
	 }
	 if (!xdr_nfstime3(xdrs, &objp->mtime)) {
		 return (FALSE);
	 }
	 if (!xdr_nfstime3(xdrs, &objp->ctime)) {
		 return (FALSE);
	 }
	 if (!xdr_uint32(xdrs, &objp->expire)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_ex_post_op_attr(XDR *xdrs, ex_post_op_attr *objp)
{

	 register int32_t *buf;

	 if (!xdr_bool(xdrs, &objp->present)) {
		 return (FALSE);
	 }
	switch (objp->present) {
	case TRUE:
		 if (!xdr_ex_fattr3(xdrs, &objp->RPC_UNION_NAME(ex_post_op_attr).attributes)) {
			 return (FALSE);
		 }
		break;
	case FALSE:
		break;
	default:
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_ex_wcc_data(XDR *xdrs, ex_wcc_data *objp)
{

	 register int32_t *buf;

	 if (!xdr_pre_op_attr(xdrs, &objp->before)) {
		 return (FALSE);
	 }
	 if (!xdr_ex_post_op_attr(xdrs, &objp->after)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_ex_diropres3ok(XDR *xdrs, ex_diropres3ok *objp)
{

	 register int32_t *buf;

	 if (!xdr_post_op_fh3(xdrs, &objp->obj)) {
		 return (FALSE);
	 }
	 if (!xdr_ex_post_op_attr(xdrs, &objp->obj_attributes)) {
		 return (FALSE);
	 }
	 if (!xdr_ex_wcc_data(xdrs, &objp->dir_wcc)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_ex_diropres3(XDR *xdrs, ex_diropres3 *objp)
{

	 register int32_t *buf;

	 if (!xdr_nfsstat3(xdrs, &objp->status)) {
		 return (FALSE);
	 }
	switch (objp->status) {
	case NFS3_OK:
		 if (!xdr_ex_diropres3ok(xdrs, &objp->RPC_UNION_NAME(ex_diropres3).resok)) {
			 return (FALSE);
		 }
		break;
	default:
		 if (!xdr_ex_wcc_data(xdrs, &objp->RPC_UNION_NAME(ex_diropres3).resfail)) {
			 return (FALSE);
		 }
		break;
	}
	return (TRUE);
}

bool_t
xdr_ex_wccstat3(XDR *xdrs, ex_wccstat3 *objp)
{

	 register int32_t *buf;

	 if (!xdr_nfsstat3(xdrs, &objp->status)) {
		 return (FALSE);
	 }
	switch (objp->status) {
	case -1:
		break;
	default:
		 if (!xdr_ex_wcc_data(xdrs, &objp->RPC_UNION_NAME(ex_wccstat3).wcc)) {
			 return (FALSE);
		 }
		break;
	}
	return (TRUE);
}

bool_t
xdr_ex_getattr3res(XDR *xdrs, ex_getattr3res *objp)
{

	 register int32_t *buf;

	 if (!xdr_nfsstat3(xdrs, &objp->status)) {
		 return (FALSE);
	 }
	switch (objp->status) {
	case NFS3_OK:
		 if (!xdr_ex_fattr3(xdrs, &objp->RPC_UNION_NAME(ex_getattr3res).attributes)) {
			 return (FALSE);
		 }
		break;
	}
	return (TRUE);
}

bool_t
xdr_ex_lookup3resok(XDR *xdrs, ex_lookup3resok *objp)
{

	 register int32_t *buf;

	 if (!xdr_nfs_fh3(xdrs, &objp->object)) {
		 return (FALSE);
	 }
	 if (!xdr_ex_post_op_attr(xdrs, &objp->obj_attributes)) {
		 return (FALSE);
	 }
	 if (!xdr_ex_post_op_attr(xdrs, &objp->dir_attributes)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_ex_lookup3res(XDR *xdrs, ex_lookup3res *objp)
{

	 register int32_t *buf;

	 if (!xdr_nfsstat3(xdrs, &objp->status)) {
		 return (FALSE);
	 }
	switch (objp->status) {
	case NFS3_OK:
		 if (!xdr_ex_lookup3resok(xdrs, &objp->RPC_UNION_NAME(ex_lookup3res).resok)) {
			 return (FALSE);
		 }
		break;
	default:
		 if (!xdr_ex_post_op_attr(xdrs, &objp->RPC_UNION_NAME(ex_lookup3res).resfail)) {
			 return (FALSE);
		 }
		break;
	}
	return (TRUE);
}

bool_t
xdr_ex_access3resok(XDR *xdrs, ex_access3resok *objp)
{

	 register int32_t *buf;

	 if (!xdr_ex_post_op_attr(xdrs, &objp->obj_attributes)) {
		 return (FALSE);
	 }
	 if (!xdr_uint32(xdrs, &objp->access)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_ex_access3res(XDR *xdrs, ex_access3res *objp)
{

	 register int32_t *buf;

	 if (!xdr_nfsstat3(xdrs, &objp->status)) {
		 return (FALSE);
	 }
	switch (objp->status) {
	case NFS3_OK:
		 if (!xdr_ex_access3resok(xdrs, &objp->RPC_UNION_NAME(ex_access3res).resok)) {
			 return (FALSE);
		 }
		break;
	default:
		 if (!xdr_ex_post_op_attr(xdrs, &objp->RPC_UNION_NAME(ex_access3res).resfail)) {
			 return (FALSE);
		 }
		break;
	}
	return (TRUE);
}

bool_t
xdr_ex_readlink3resok(XDR *xdrs, ex_readlink3resok *objp)
{

	 register int32_t *buf;

	 if (!xdr_ex_post_op_attr(xdrs, &objp->symlink_attributes)) {
		 return (FALSE);
	 }
	 if (!xdr_nfspath3(xdrs, &objp->data)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_ex_readlink3res(XDR *xdrs, ex_readlink3res *objp)
{

	 register int32_t *buf;

	 if (!xdr_nfsstat3(xdrs, &objp->status)) {
		 return (FALSE);
	 }
	switch (objp->status) {
	case NFS3_OK:
		 if (!xdr_ex_readlink3resok(xdrs, &objp->RPC_UNION_NAME(ex_readlink3res).resok)) {
			 return (FALSE);
		 }
		break;
	default:
		 if (!xdr_ex_post_op_attr(xdrs, &objp->RPC_UNION_NAME(ex_readlink3res).resfail)) {
			 return (FALSE);
		 }
		break;
	}
	return (TRUE);
}

bool_t
xdr_ex_read3resok(XDR *xdrs, ex_read3resok *objp)
{

	 register int32_t *buf;

	 if (!xdr_ex_post_op_attr(xdrs, &objp->file_attributes)) {
		 return (FALSE);
	 }
	 if (!xdr_uint32(xdrs, &objp->count)) {
		 return (FALSE);
	 }
	 if (!xdr_bool(xdrs, &objp->eof)) {
		 return (FALSE);
	 }
	 if (!xdr_bytes(xdrs, (char **)&objp->data.val, (u_int *)&objp->data.len, ~0)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_ex_read3res(XDR *xdrs, ex_read3res *objp)
{

	 register int32_t *buf;

	 if (!xdr_nfsstat3(xdrs, &objp->status)) {
		 return (FALSE);
	 }
	switch (objp->status) {
	case NFS3_OK:
		 if (!xdr_ex_read3resok(xdrs, &objp->RPC_UNION_NAME(ex_read3res).resok)) {
			 return (FALSE);
		 }
		break;
	default:
		 if (!xdr_ex_post_op_attr(xdrs, &objp->RPC_UNION_NAME(ex_read3res).resfail)) {
			 return (FALSE);
		 }
		break;
	}
	return (TRUE);
}

bool_t
xdr_ex_write3resok(XDR *xdrs, ex_write3resok *objp)
{

	 register int32_t *buf;

	 if (!xdr_ex_wcc_data(xdrs, &objp->file_wcc)) {
		 return (FALSE);
	 }
	 if (!xdr_uint32(xdrs, &objp->count)) {
		 return (FALSE);
	 }
	 if (!xdr_stable_how(xdrs, &objp->committed)) {
		 return (FALSE);
	 }
	 if (!xdr_writeverf3(xdrs, &objp->verf)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_ex_write3res(XDR *xdrs, ex_write3res *objp)
{

	 register int32_t *buf;

	 if (!xdr_nfsstat3(xdrs, &objp->status)) {
		 return (FALSE);
	 }
	switch (objp->status) {
	case NFS3_OK:
		 if (!xdr_ex_write3resok(xdrs, &objp->RPC_UNION_NAME(ex_write3res).resok)) {
			 return (FALSE);
		 }
		break;
	default:
		 if (!xdr_ex_wcc_data(xdrs, &objp->RPC_UNION_NAME(ex_write3res).resfail)) {
			 return (FALSE);
		 }
		break;
	}
	return (TRUE);
}

bool_t
xdr_ex_rename3wcc(XDR *xdrs, ex_rename3wcc *objp)
{

	 register int32_t *buf;

	 if (!xdr_ex_wcc_data(xdrs, &objp->fromdir_wcc)) {
		 return (FALSE);
	 }
	 if (!xdr_ex_wcc_data(xdrs, &objp->todir_wcc)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_ex_rename3res(XDR *xdrs, ex_rename3res *objp)
{

	 register int32_t *buf;

	 if (!xdr_nfsstat3(xdrs, &objp->status)) {
		 return (FALSE);
	 }
	switch (objp->status) {
	case -1:
		break;
	default:
		 if (!xdr_ex_rename3wcc(xdrs, &objp->RPC_UNION_NAME(ex_rename3res).res)) {
			 return (FALSE);
		 }
		break;
	}
	return (TRUE);
}

bool_t
xdr_ex_link3wcc(XDR *xdrs, ex_link3wcc *objp)
{

	 register int32_t *buf;

	 if (!xdr_ex_post_op_attr(xdrs, &objp->file_attributes)) {
		 return (FALSE);
	 }
	 if (!xdr_ex_wcc_data(xdrs, &objp->linkdir_wcc)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_ex_link3res(XDR *xdrs, ex_link3res *objp)
{

	 register int32_t *buf;

	 if (!xdr_nfsstat3(xdrs, &objp->status)) {
		 return (FALSE);
	 }
	switch (objp->status) {
	case -1:
		break;
	default:
		 if (!xdr_ex_link3wcc(xdrs, &objp->RPC_UNION_NAME(ex_link3res).res)) {
			 return (FALSE);
		 }
		break;
	}
	return (TRUE);
}

bool_t
xdr_ex_readdir3resok(XDR *xdrs, ex_readdir3resok *objp)
{

	 register int32_t *buf;

	 if (!xdr_ex_post_op_attr(xdrs, &objp->dir_attributes)) {
		 return (FALSE);
	 }
	 if (!xdr_cookieverf3(xdrs, &objp->cookieverf)) {
		 return (FALSE);
	 }
	 if (!xdr_dirlist3(xdrs, &objp->reply)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_ex_readdir3res(XDR *xdrs, ex_readdir3res *objp)
{

	 register int32_t *buf;

	 if (!xdr_nfsstat3(xdrs, &objp->status)) {
		 return (FALSE);
	 }
	switch (objp->status) {
	case NFS3_OK:
		 if (!xdr_ex_readdir3resok(xdrs, &objp->RPC_UNION_NAME(ex_readdir3res).resok)) {
			 return (FALSE);
		 }
		break;
	default:
		 if (!xdr_ex_post_op_attr(xdrs, &objp->RPC_UNION_NAME(ex_readdir3res).resfail)) {
			 return (FALSE);
		 }
		break;
	}
	return (TRUE);
}

bool_t
xdr_ex_entryplus3(XDR *xdrs, ex_entryplus3 *objp)
{

	 register int32_t *buf;

	 if (!xdr_uint64(xdrs, &objp->fileid)) {
		 return (FALSE);
	 }
	 if (!xdr_filename3(xdrs, &objp->name)) {
		 return (FALSE);
	 }
	 if (!xdr_uint64(xdrs, &objp->cookie)) {
		 return (FALSE);
	 }
	 if (!xdr_ex_post_op_attr(xdrs, &objp->name_attributes)) {
		 return (FALSE);
	 }
	 if (!xdr_post_op_fh3(xdrs, &objp->name_handle)) {
		 return (FALSE);
	 }
	 if (!xdr_pointer(xdrs, (char **)&objp->nextentry, sizeof(ex_entryplus3), (xdrproc_t)xdr_ex_entryplus3)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_ex_dirlistplus3(XDR *xdrs, ex_dirlistplus3 *objp)
{

	 register int32_t *buf;

	 if (!xdr_pointer(xdrs, (char **)&objp->entries, sizeof(ex_entryplus3), (xdrproc_t)xdr_ex_entryplus3)) {
		 return (FALSE);
	 }
	 if (!xdr_bool(xdrs, &objp->eof)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_ex_readdirplus3resok(XDR *xdrs, ex_readdirplus3resok *objp)
{

	 register int32_t *buf;

	 if (!xdr_ex_post_op_attr(xdrs, &objp->dir_attributes)) {
		 return (FALSE);
	 }
	 if (!xdr_cookieverf3(xdrs, &objp->cookieverf)) {
		 return (FALSE);
	 }
	 if (!xdr_ex_dirlistplus3(xdrs, &objp->reply)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_ex_readdirplus3res(XDR *xdrs, ex_readdirplus3res *objp)
{

	 register int32_t *buf;

	 if (!xdr_nfsstat3(xdrs, &objp->status)) {
		 return (FALSE);
	 }
	switch (objp->status) {
	case NFS3_OK:
		 if (!xdr_ex_readdirplus3resok(xdrs, &objp->RPC_UNION_NAME(ex_readdirplus3res).resok)) {
			 return (FALSE);
		 }
		break;
	default:
		 if (!xdr_ex_post_op_attr(xdrs, &objp->RPC_UNION_NAME(ex_readdirplus3res).resfail)) {
			 return (FALSE);
		 }
		break;
	}
	return (TRUE);
}

bool_t
xdr_ex_fsstat3resok(XDR *xdrs, ex_fsstat3resok *objp)
{

	 register int32_t *buf;

	 if (!xdr_ex_post_op_attr(xdrs, &objp->obj_attributes)) {
		 return (FALSE);
	 }
	 if (!xdr_uint64(xdrs, &objp->tbytes)) {
		 return (FALSE);
	 }
	 if (!xdr_uint64(xdrs, &objp->fbytes)) {
		 return (FALSE);
	 }
	 if (!xdr_uint64(xdrs, &objp->abytes)) {
		 return (FALSE);
	 }
	 if (!xdr_uint64(xdrs, &objp->tfiles)) {
		 return (FALSE);
	 }
	 if (!xdr_uint64(xdrs, &objp->ffiles)) {
		 return (FALSE);
	 }
	 if (!xdr_uint64(xdrs, &objp->afiles)) {
		 return (FALSE);
	 }
	 if (!xdr_uint32(xdrs, &objp->invarsec)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_ex_fsstat3res(XDR *xdrs, ex_fsstat3res *objp)
{

	 register int32_t *buf;

	 if (!xdr_nfsstat3(xdrs, &objp->status)) {
		 return (FALSE);
	 }
	switch (objp->status) {
	case NFS3_OK:
		 if (!xdr_ex_fsstat3resok(xdrs, &objp->RPC_UNION_NAME(ex_fsstat3res).resok)) {
			 return (FALSE);
		 }
		break;
	default:
		 if (!xdr_ex_post_op_attr(xdrs, &objp->RPC_UNION_NAME(ex_fsstat3res).resfail)) {
			 return (FALSE);
		 }
		break;
	}
	return (TRUE);
}

bool_t
xdr_ex_fsinfo3resok(XDR *xdrs, ex_fsinfo3resok *objp)
{

	 register int32_t *buf;

	 if (!xdr_ex_post_op_attr(xdrs, &objp->obj_attributes)) {
		 return (FALSE);
	 }
	 if (!xdr_uint32(xdrs, &objp->rtmax)) {
		 return (FALSE);
	 }
	 if (!xdr_uint32(xdrs, &objp->rtpref)) {
		 return (FALSE);
	 }
	 if (!xdr_uint32(xdrs, &objp->rtmult)) {
		 return (FALSE);
	 }
	 if (!xdr_uint32(xdrs, &objp->wtmax)) {
		 return (FALSE);
	 }
	 if (!xdr_uint32(xdrs, &objp->wtpref)) {
		 return (FALSE);
	 }
	 if (!xdr_uint32(xdrs, &objp->wtmult)) {
		 return (FALSE);
	 }
	 if (!xdr_uint32(xdrs, &objp->dtpref)) {
		 return (FALSE);
	 }
	 if (!xdr_uint64(xdrs, &objp->maxfilesize)) {
		 return (FALSE);
	 }
	 if (!xdr_nfstime3(xdrs, &objp->time_delta)) {
		 return (FALSE);
	 }
	 if (!xdr_uint32(xdrs, &objp->properties)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_ex_fsinfo3res(XDR *xdrs, ex_fsinfo3res *objp)
{

	 register int32_t *buf;

	 if (!xdr_nfsstat3(xdrs, &objp->status)) {
		 return (FALSE);
	 }
	switch (objp->status) {
	case NFS3_OK:
		 if (!xdr_ex_fsinfo3resok(xdrs, &objp->RPC_UNION_NAME(ex_fsinfo3res).resok)) {
			 return (FALSE);
		 }
		break;
	default:
		 if (!xdr_ex_post_op_attr(xdrs, &objp->RPC_UNION_NAME(ex_fsinfo3res).resfail)) {
			 return (FALSE);
		 }
		break;
	}
	return (TRUE);
}

bool_t
xdr_ex_pathconf3resok(XDR *xdrs, ex_pathconf3resok *objp)
{

	 register int32_t *buf;


	 if (xdrs->x_op == XDR_ENCODE) {
	 if (!xdr_ex_post_op_attr(xdrs, &objp->obj_attributes)) {
		 return (FALSE);
	 }
	 if (!xdr_uint32(xdrs, &objp->linkmax)) {
		 return (FALSE);
	 }
	 if (!xdr_uint32(xdrs, &objp->name_max)) {
		 return (FALSE);
	 }
		buf = (int32_t *)XDR_INLINE(xdrs,4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
		 if (!xdr_bool(xdrs, &objp->no_trunc)) {
			 return (FALSE);
		 }
		 if (!xdr_bool(xdrs, &objp->chown_restricted)) {
			 return (FALSE);
		 }
		 if (!xdr_bool(xdrs, &objp->case_insensitive)) {
			 return (FALSE);
		 }
		 if (!xdr_bool(xdrs, &objp->case_preserving)) {
			 return (FALSE);
		 }

	  }
	  else {
		 IXDR_PUT_BOOL(buf,objp->no_trunc);
		 IXDR_PUT_BOOL(buf,objp->chown_restricted);
		 IXDR_PUT_BOOL(buf,objp->case_insensitive);
		 IXDR_PUT_BOOL(buf,objp->case_preserving);
	  }

 	 return (TRUE);
	} else if (xdrs->x_op == XDR_DECODE) {
	 if (!xdr_ex_post_op_attr(xdrs, &objp->obj_attributes)) {
		 return (FALSE);
	 }
	 if (!xdr_uint32(xdrs, &objp->linkmax)) {
		 return (FALSE);
	 }
	 if (!xdr_uint32(xdrs, &objp->name_max)) {
		 return (FALSE);
	 }
		buf = (int32_t *)XDR_INLINE(xdrs,4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
		 if (!xdr_bool(xdrs, &objp->no_trunc)) {
			 return (FALSE);
		 }
		 if (!xdr_bool(xdrs, &objp->chown_restricted)) {
			 return (FALSE);
		 }
		 if (!xdr_bool(xdrs, &objp->case_insensitive)) {
			 return (FALSE);
		 }
		 if (!xdr_bool(xdrs, &objp->case_preserving)) {
			 return (FALSE);
		 }

	  }
	  else {
		 objp->no_trunc = IXDR_GET_BOOL(buf);
		 objp->chown_restricted = IXDR_GET_BOOL(buf);
		 objp->case_insensitive = IXDR_GET_BOOL(buf);
		 objp->case_preserving = IXDR_GET_BOOL(buf);
	  }
	 return(TRUE);
	}

	 if (!xdr_ex_post_op_attr(xdrs, &objp->obj_attributes)) {
		 return (FALSE);
	 }
	 if (!xdr_uint32(xdrs, &objp->linkmax)) {
		 return (FALSE);
	 }
	 if (!xdr_uint32(xdrs, &objp->name_max)) {
		 return (FALSE);
	 }
	 if (!xdr_bool(xdrs, &objp->no_trunc)) {
		 return (FALSE);
	 }
	 if (!xdr_bool(xdrs, &objp->chown_restricted)) {
		 return (FALSE);
	 }
	 if (!xdr_bool(xdrs, &objp->case_insensitive)) {
		 return (FALSE);
	 }
	 if (!xdr_bool(xdrs, &objp->case_preserving)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_ex_pathconf3res(XDR *xdrs, ex_pathconf3res *objp)
{

	 register int32_t *buf;

	 if (!xdr_nfsstat3(xdrs, &objp->status)) {
		 return (FALSE);
	 }
	switch (objp->status) {
	case NFS3_OK:
		 if (!xdr_ex_pathconf3resok(xdrs, &objp->RPC_UNION_NAME(ex_pathconf3res).resok)) {
			 return (FALSE);
		 }
		break;
	default:
		 if (!xdr_ex_post_op_attr(xdrs, &objp->RPC_UNION_NAME(ex_pathconf3res).resfail)) {
			 return (FALSE);
		 }
		break;
	}
	return (TRUE);
}

bool_t
xdr_ex_commit3resok(XDR *xdrs, ex_commit3resok *objp)
{

	 register int32_t *buf;

	 if (!xdr_ex_wcc_data(xdrs, &objp->file_wcc)) {
		 return (FALSE);
	 }
	 if (!xdr_writeverf3(xdrs, &objp->verf)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_ex_commit3res(XDR *xdrs, ex_commit3res *objp)
{

	 register int32_t *buf;

	 if (!xdr_nfsstat3(xdrs, &objp->status)) {
		 return (FALSE);
	 }
	switch (objp->status) {
	case NFS3_OK:
		 if (!xdr_ex_commit3resok(xdrs, &objp->RPC_UNION_NAME(ex_commit3res).resok)) {
			 return (FALSE);
		 }
		break;
	default:
		 if (!xdr_ex_wcc_data(xdrs, &objp->RPC_UNION_NAME(ex_commit3res).resfail)) {
			 return (FALSE);
		 }
		break;
	}
	return (TRUE);
}

bool_t
xdr_ex_invalidate3args(XDR *xdrs, ex_invalidate3args *objp)
{

	 register int32_t *buf;

	 if (!xdr_nfs_fh3(xdrs, &objp->handle)) {
		 return (FALSE);
	 }
	 if (!xdr_ex_post_op_attr(xdrs, &objp->attributes)) {
		 return (FALSE);
	 }
	return (TRUE);
}

const struct rpcgen_table ex_nfs_program_3_table[] = {
    {
	(char *(*)())RPCGEN_ACTION(ex_nfsproc3_null_3_svc),
	(xdrproc_t) xdr_void,		0,
	(xdrproc_t) xdr_void,		0,
    },
    {
	(char *(*)())RPCGEN_ACTION(ex_nfsproc3_getattr_3_svc),
	(xdrproc_t) xdr_nfs_fh3,	sizeof ( nfs_fh3 ),
	(xdrproc_t) xdr_ex_getattr3res,	sizeof ( ex_getattr3res ),
    },
    {
	(char *(*)())RPCGEN_ACTION(ex_nfsproc3_setattr_3_svc),
	(xdrproc_t) xdr_setattr3args,	sizeof ( setattr3args ),
	(xdrproc_t) xdr_ex_wccstat3,	sizeof ( ex_wccstat3 ),
    },
    {
	(char *(*)())RPCGEN_ACTION(ex_nfsproc3_lookup_3_svc),
	(xdrproc_t) xdr_diropargs3,	sizeof ( diropargs3 ),
	(xdrproc_t) xdr_ex_lookup3res,	sizeof ( ex_lookup3res ),
    },
    {
	(char *(*)())RPCGEN_ACTION(ex_nfsproc3_access_3_svc),
	(xdrproc_t) xdr_access3args,	sizeof ( access3args ),
	(xdrproc_t) xdr_ex_access3res,	sizeof ( ex_access3res ),
    },
    {
	(char *(*)())RPCGEN_ACTION(ex_nfsproc3_readlink_3_svc),
	(xdrproc_t) xdr_nfs_fh3,	sizeof ( nfs_fh3 ),
	(xdrproc_t) xdr_ex_readlink3res,sizeof ( ex_readlink3res ),
    },
    {
	(char *(*)())RPCGEN_ACTION(ex_nfsproc3_read_3_svc),
	(xdrproc_t) xdr_read3args,	sizeof ( read3args ),
	(xdrproc_t) xdr_ex_read3res,	sizeof ( ex_read3res ),
    },
    {
	(char *(*)())RPCGEN_ACTION(ex_nfsproc3_write_3_svc),
	(xdrproc_t) xdr_write3args,	sizeof ( write3args ),
	(xdrproc_t) xdr_ex_write3res,	sizeof ( ex_write3res ),
    },
    {
	(char *(*)())RPCGEN_ACTION(ex_nfsproc3_create_3_svc),
	(xdrproc_t) xdr_create3args,	sizeof ( create3args ),
	(xdrproc_t) xdr_ex_diropres3,	sizeof ( ex_diropres3 ),
    },
    {
	(char *(*)())RPCGEN_ACTION(ex_nfsproc3_mkdir_3_svc),
	(xdrproc_t) xdr_mkdir3args,	sizeof ( mkdir3args ),
	(xdrproc_t) xdr_ex_diropres3,	sizeof ( ex_diropres3 ),
    },
    {
	(char *(*)())RPCGEN_ACTION(ex_nfsproc3_symlink_3_svc),
	(xdrproc_t) xdr_symlink3args,	sizeof ( symlink3args ),
	(xdrproc_t) xdr_ex_diropres3,	sizeof ( ex_diropres3 ),
    },
    {
	(char *(*)())RPCGEN_ACTION(ex_nfsproc3_mknod_3_svc),
	(xdrproc_t) xdr_mknod3args,	sizeof ( mknod3args ),
	(xdrproc_t) xdr_ex_diropres3,	sizeof ( ex_diropres3 ),
    },
    {
	(char *(*)())RPCGEN_ACTION(ex_nfsproc3_remove_3_svc),
	(xdrproc_t) xdr_diropargs3,	sizeof ( diropargs3 ),
	(xdrproc_t) xdr_ex_wccstat3,	sizeof ( ex_wccstat3 ),
    },
    {
	(char *(*)())RPCGEN_ACTION(ex_nfsproc3_rmdir_3_svc),
	(xdrproc_t) xdr_diropargs3,	sizeof ( diropargs3 ),
	(xdrproc_t) xdr_ex_wccstat3,	sizeof ( ex_wccstat3 ),
    },
    {
	(char *(*)())RPCGEN_ACTION(ex_nfsproc3_rename_3_svc),
	(xdrproc_t) xdr_rename3args,	sizeof ( rename3args ),
	(xdrproc_t) xdr_ex_rename3res,	sizeof ( ex_rename3res ),
    },
    {
	(char *(*)())RPCGEN_ACTION(ex_nfsproc3_link_3_svc),
	(xdrproc_t) xdr_link3args,	sizeof ( link3args ),
	(xdrproc_t) xdr_ex_link3res,	sizeof ( ex_link3res ),
    },
    {
	(char *(*)())RPCGEN_ACTION(ex_nfsproc3_readdir_3_svc),
	(xdrproc_t) xdr_readdir3args,	sizeof ( readdir3args ),
	(xdrproc_t) xdr_ex_readdir3res,	sizeof ( ex_readdir3res ),
    },
    {
	(char *(*)())RPCGEN_ACTION(ex_nfsproc3_readdirplus_3_svc),
	(xdrproc_t) xdr_readdirplus3args,sizeof ( readdirplus3args ),
	(xdrproc_t) xdr_ex_readdirplus3res,sizeof ( ex_readdirplus3res ),
    },
    {
	(char *(*)())RPCGEN_ACTION(ex_nfsproc3_fsstat_3_svc),
	(xdrproc_t) xdr_nfs_fh3,	sizeof ( nfs_fh3 ),
	(xdrproc_t) xdr_ex_fsstat3res,	sizeof ( ex_fsstat3res ),
    },
    {
	(char *(*)())RPCGEN_ACTION(ex_nfsproc3_fsinfo_3_svc),
	(xdrproc_t) xdr_nfs_fh3,	sizeof ( nfs_fh3 ),
	(xdrproc_t) xdr_ex_fsinfo3res,	sizeof ( ex_fsinfo3res ),
    },
    {
	(char *(*)())RPCGEN_ACTION(ex_nfsproc3_pathconf_3_svc),
	(xdrproc_t) xdr_nfs_fh3,	sizeof ( nfs_fh3 ),
	(xdrproc_t) xdr_ex_pathconf3res,sizeof ( ex_pathconf3res ),
    },
    {
	(char *(*)())RPCGEN_ACTION(ex_nfsproc3_commit_3_svc),
	(xdrproc_t) xdr_commit3args,	sizeof ( commit3args ),
	(xdrproc_t) xdr_ex_commit3res,	sizeof ( ex_commit3res ),
    },
};
const int ex_nfs_program_3_nproc =
	sizeof(ex_nfs_program_3_table)/sizeof(ex_nfs_program_3_table[0]);
const struct rpc_program ex_nfs_program_3 = {
	ex_NFS_PROGRAM, 3, ex_nfs_program_3_table,
	sizeof (ex_nfs_program_3_table) / sizeof (ex_nfs_program_3_table[0])
};

const struct rpcgen_table ex_nfscb_program_3_table[] = {
    {
	(char *(*)())RPCGEN_ACTION(ex_nfscbproc3_null_3_svc),
	(xdrproc_t) xdr_void,		0,
	(xdrproc_t) xdr_void,		0,
    },
    {
	(char *(*)())RPCGEN_ACTION(ex_nfscbproc3_invalidate_3_svc),
	(xdrproc_t) xdr_ex_invalidate3args,sizeof ( ex_invalidate3args ),
	(xdrproc_t) xdr_void,		0,
    },
};
const int ex_nfscb_program_3_nproc =
	sizeof(ex_nfscb_program_3_table)/sizeof(ex_nfscb_program_3_table[0]);
const struct rpc_program ex_nfscb_program_3 = {
	ex_NFSCB_PROGRAM, 3, ex_nfscb_program_3_table,
	sizeof (ex_nfscb_program_3_table) / sizeof (ex_nfscb_program_3_table[0])
};

