// -*-c++-*-
/* This file was automatically generated by rpcc. */

#include "uvfs_prot.h"

#ifdef MAINTAINER

void
print_uvfs_fh (const void *_objp, const strbuf *_sbp, int _recdepth,
               const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_fh *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_fh (const uvfs_fh *objp)
{
  rpc_print (warnx, *objp);
}

void
print_uvfs_fattr (const void *_objp, const strbuf *_sbp, int _recdepth,
                  const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_fattr *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_fattr (const uvfs_fattr *objp)
{
  rpc_print (warnx, *objp);
}

void
print_uvfs_attrres (const void *_objp, const strbuf *_sbp, int _recdepth,
                    const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_attrres *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_attrres (const uvfs_attrres *objp)
{
  rpc_print (warnx, *objp);
}

void
print_uvfs_wccstat (const void *_objp, const strbuf *_sbp, int _recdepth,
                    const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_wccstat *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_wccstat (const uvfs_wccstat *objp)
{
  rpc_print (warnx, *objp);
}

void
print_uvfs_accessres (const void *_objp, const strbuf *_sbp, int _recdepth,
                      const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_accessres *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_accessres (const uvfs_accessres *objp)
{
  rpc_print (warnx, *objp);
}

void
print_uvfs_readlinkres (const void *_objp, const strbuf *_sbp, int _recdepth,
                        const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_readlinkres *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_readlinkres (const uvfs_readlinkres *objp)
{
  rpc_print (warnx, *objp);
}

void
print_uvfs_readres (const void *_objp, const strbuf *_sbp, int _recdepth,
                    const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_readres *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_readres (const uvfs_readres *objp)
{
  rpc_print (warnx, *objp);
}

void
print_uvfs_writeres (const void *_objp, const strbuf *_sbp, int _recdepth,
                     const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_writeres *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_writeres (const uvfs_writeres *objp)
{
  rpc_print (warnx, *objp);
}

void
print_uvfs_renameres (const void *_objp, const strbuf *_sbp, int _recdepth,
                      const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_renameres *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_renameres (const uvfs_renameres *objp)
{
  rpc_print (warnx, *objp);
}

void
print_uvfs_linkres (const void *_objp, const strbuf *_sbp, int _recdepth,
                    const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_linkres *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_linkres (const uvfs_linkres *objp)
{
  rpc_print (warnx, *objp);
}

void
print_uvfs_statfsres (const void *_objp, const strbuf *_sbp, int _recdepth,
                      const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_statfsres *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_statfsres (const uvfs_statfsres *objp)
{
  rpc_print (warnx, *objp);
}

void
print_uvfs_commitres (const void *_objp, const strbuf *_sbp, int _recdepth,
                      const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_commitres *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_commitres (const uvfs_commitres *objp)
{
  rpc_print (warnx, *objp);
}

void
print_uvfs_filename (const void *_objp, const strbuf *_sbp, int _recdepth,
                     const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_filename *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_filename (const uvfs_filename *objp)
{
  rpc_print (warnx, *objp);
}

void
print_uvfs_pathname (const void *_objp, const strbuf *_sbp, int _recdepth,
                     const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_pathname *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_pathname (const uvfs_pathname *objp)
{
  rpc_print (warnx, *objp);
}

void
print_uvfs_time (const void *_objp, const strbuf *_sbp, int _recdepth,
                 const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_time *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_time (const uvfs_time *objp)
{
  rpc_print (warnx, *objp);
}

void
print_uvfs_sattr (const void *_objp, const strbuf *_sbp, int _recdepth,
                  const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_sattr *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_sattr (const uvfs_sattr *objp)
{
  rpc_print (warnx, *objp);
}

void
print_uvfs_guard (const void *_objp, const strbuf *_sbp, int _recdepth,
                  const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_guard *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_guard (const uvfs_guard *objp)
{
  rpc_print (warnx, *objp);
}

void
print_uvfsstat (const void *_objp, const strbuf *_sbp, int _recdepth,
                const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfsstat *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfsstat (const uvfsstat *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const uvfs_readdirargs &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "uvfs_readdirargs " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.dir, recdepth, "dir", npref);
  sb << sep;
  rpc_print (sb, obj.cookie, recdepth, "cookie", npref);
  sb << sep;
  rpc_print (sb, obj.count, recdepth, "count", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_uvfs_readdirargs (const void *_objp, const strbuf *_sbp, int _recdepth,
                        const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_readdirargs *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_readdirargs (const uvfs_readdirargs *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const uvfs_direntry &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "uvfs_direntry " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.fileid, recdepth, "fileid", npref);
  sb << sep;
  rpc_print (sb, obj.cookie, recdepth, "cookie", npref);
  sb << sep;
  rpc_print (sb, obj.type, recdepth, "type", npref);
  sb << sep;
  rpc_print (sb, obj.name, recdepth, "name", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_uvfs_direntry (const void *_objp, const strbuf *_sbp, int _recdepth,
                     const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_direntry *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_direntry (const uvfs_direntry *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const uvfs_dirlist &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "uvfs_dirlist " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.entries, recdepth, "entries", npref);
  sb << sep;
  rpc_print (sb, obj.eof, recdepth, "eof", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_uvfs_dirlist (const void *_objp, const strbuf *_sbp, int _recdepth,
                    const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_dirlist *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_dirlist (const uvfs_dirlist *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const uvfs_readdirres &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "uvfs_readdirres " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.status, recdepth, "status", npref);
  switch (obj.status) {
  case 0:
    sb << sep;
    rpc_print (sb, *obj.reply,  recdepth, "reply", npref);
    break;
  default:
    break;
  }
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_uvfs_readdirres (const void *_objp, const strbuf *_sbp, int _recdepth,
                       const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_readdirres *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_readdirres (const uvfs_readdirres *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const uvfs_setattrargs &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "uvfs_setattrargs " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.file, recdepth, "file", npref);
  sb << sep;
  rpc_print (sb, obj.attributes, recdepth, "attributes", npref);
  sb << sep;
  rpc_print (sb, obj.guard, recdepth, "guard", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_uvfs_setattrargs (const void *_objp, const strbuf *_sbp, int _recdepth,
                        const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_setattrargs *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_setattrargs (const uvfs_setattrargs *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const post_op_uvfs_fh &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "post_op_uvfs_fh " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.present, recdepth, "present", npref);
  switch (obj.present) {
  case true:
    sb << sep;
    rpc_print (sb, *obj.handle,  recdepth, "handle", npref);
    break;
  case false:
    break;
  default:
    break;
  }
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_post_op_uvfs_fh (const void *_objp, const strbuf *_sbp, int _recdepth,
                       const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const post_op_uvfs_fh *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_post_op_uvfs_fh (const post_op_uvfs_fh *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const uvfs_diropargs &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "uvfs_diropargs " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.dir, recdepth, "dir", npref);
  sb << sep;
  rpc_print (sb, obj.name, recdepth, "name", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_uvfs_diropargs (const void *_objp, const strbuf *_sbp, int _recdepth,
                      const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_diropargs *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_diropargs (const uvfs_diropargs *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const uvfs_diropresok &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "uvfs_diropresok " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.file, recdepth, "file", npref);
  sb << sep;
  rpc_print (sb, obj.attributes, recdepth, "attributes", npref);
  sb << sep;
  rpc_print (sb, obj.dir_wcc, recdepth, "dir_wcc", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_uvfs_diropresok (const void *_objp, const strbuf *_sbp, int _recdepth,
                       const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_diropresok *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_diropresok (const uvfs_diropresok *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const uvfs_diropres &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "uvfs_diropres " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.status, recdepth, "status", npref);
  switch (obj.status) {
  case 0:
    sb << sep;
    rpc_print (sb, *obj.resok,  recdepth, "resok", npref);
    break;
  default:
    sb << sep;
    rpc_print (sb, *obj.resfail,  recdepth, "resfail", npref);
    break;
  }
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_uvfs_diropres (const void *_objp, const strbuf *_sbp, int _recdepth,
                     const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_diropres *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_diropres (const uvfs_diropres *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const uvfs_readargs &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "uvfs_readargs " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.file, recdepth, "file", npref);
  sb << sep;
  rpc_print (sb, obj.offset, recdepth, "offset", npref);
  sb << sep;
  rpc_print (sb, obj.count, recdepth, "count", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_uvfs_readargs (const void *_objp, const strbuf *_sbp, int _recdepth,
                     const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_readargs *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_readargs (const uvfs_readargs *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const uvfs_writeargs &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "uvfs_writeargs " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.file, recdepth, "file", npref);
  sb << sep;
  rpc_print (sb, obj.offset, recdepth, "offset", npref);
  sb << sep;
  rpc_print (sb, obj.count, recdepth, "count", npref);
  sb << sep;
  rpc_print (sb, obj.stable, recdepth, "stable", npref);
  sb << sep;
  rpc_print (sb, obj.data, recdepth, "data", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_uvfs_writeargs (const void *_objp, const strbuf *_sbp, int _recdepth,
                      const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_writeargs *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_writeargs (const uvfs_writeargs *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const uvfs_createargs &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "uvfs_createargs " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.where, recdepth, "where", npref);
  sb << sep;
  rpc_print (sb, obj.how, recdepth, "how", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_uvfs_createargs (const void *_objp, const strbuf *_sbp, int _recdepth,
                       const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_createargs *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_createargs (const uvfs_createargs *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const uvfs_mkdirargs &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "uvfs_mkdirargs " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.where, recdepth, "where", npref);
  sb << sep;
  rpc_print (sb, obj.attributes, recdepth, "attributes", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_uvfs_mkdirargs (const void *_objp, const strbuf *_sbp, int _recdepth,
                      const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_mkdirargs *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_mkdirargs (const uvfs_mkdirargs *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const uvfs_renameargs &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "uvfs_renameargs " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.from, recdepth, "from", npref);
  sb << sep;
  rpc_print (sb, obj.to, recdepth, "to", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_uvfs_renameargs (const void *_objp, const strbuf *_sbp, int _recdepth,
                       const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_renameargs *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_renameargs (const uvfs_renameargs *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const uvfs_commitargs &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "uvfs_commitargs " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.file, recdepth, "file", npref);
  sb << sep;
  rpc_print (sb, obj.offset, recdepth, "offset", npref);
  sb << sep;
  rpc_print (sb, obj.count, recdepth, "count", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_uvfs_commitargs (const void *_objp, const strbuf *_sbp, int _recdepth,
                       const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_commitargs *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_commitargs (const uvfs_commitargs *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const uvfs_linkargs &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "uvfs_linkargs " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.from, recdepth, "from", npref);
  sb << sep;
  rpc_print (sb, obj.to, recdepth, "to", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_uvfs_linkargs (const void *_objp, const strbuf *_sbp, int _recdepth,
                     const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_linkargs *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_linkargs (const uvfs_linkargs *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const uvfs_symlinkargs &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "uvfs_symlinkargs " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.where, recdepth, "where", npref);
  sb << sep;
  rpc_print (sb, obj.symlink, recdepth, "symlink", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_uvfs_symlinkargs (const void *_objp, const strbuf *_sbp, int _recdepth,
                        const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_symlinkargs *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_symlinkargs (const uvfs_symlinkargs *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const uvfs_accessargs &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "uvfs_accessargs " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.object, recdepth, "object", npref);
  sb << sep;
  rpc_print (sb, obj.access, recdepth, "access", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_uvfs_accessargs (const void *_objp, const strbuf *_sbp, int _recdepth,
                       const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_accessargs *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_accessargs (const uvfs_accessargs *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const uvfs_lookupresok &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "uvfs_lookupresok " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.object, recdepth, "object", npref);
  sb << sep;
  rpc_print (sb, obj.obj_attributes, recdepth, "obj_attributes", npref);
  sb << sep;
  rpc_print (sb, obj.dir_attributes, recdepth, "dir_attributes", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_uvfs_lookupresok (const void *_objp, const strbuf *_sbp, int _recdepth,
                        const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_lookupresok *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_lookupresok (const uvfs_lookupresok *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const uvfs_lookupres &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "uvfs_lookupres " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.status, recdepth, "status", npref);
  switch (obj.status) {
  case 0:
    sb << sep;
    rpc_print (sb, *obj.resok,  recdepth, "resok", npref);
    break;
  default:
    sb << sep;
    rpc_print (sb, *obj.resfail,  recdepth, "resfail", npref);
    break;
  }
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_uvfs_lookupres (const void *_objp, const strbuf *_sbp, int _recdepth,
                      const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_lookupres *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_lookupres (const uvfs_lookupres *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const uvfs_invalidateargs &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "uvfs_invalidateargs " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.handle, recdepth, "handle", npref);
  sb << sep;
  rpc_print (sb, obj.attributes, recdepth, "attributes", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_uvfs_invalidateargs (const void *_objp, const strbuf *_sbp, int _recdepth,
                           const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const uvfs_invalidateargs *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_uvfs_invalidateargs (const uvfs_invalidateargs *objp)
{
  rpc_print (warnx, *objp);
}

#endif /* MAINTAINER*/
void *
uvfs_fh_alloc ()
{
  return New uvfs_fh;
}
bool_t
xdr_uvfs_fh (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_fh *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_fh *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_fattr_alloc ()
{
  return New uvfs_fattr;
}
bool_t
xdr_uvfs_fattr (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_fattr *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_fattr *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_attrres_alloc ()
{
  return New uvfs_attrres;
}
bool_t
xdr_uvfs_attrres (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_attrres *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_attrres *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_wccstat_alloc ()
{
  return New uvfs_wccstat;
}
bool_t
xdr_uvfs_wccstat (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_wccstat *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_wccstat *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_accessres_alloc ()
{
  return New uvfs_accessres;
}
bool_t
xdr_uvfs_accessres (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_accessres *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_accessres *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_readlinkres_alloc ()
{
  return New uvfs_readlinkres;
}
bool_t
xdr_uvfs_readlinkres (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_readlinkres *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_readlinkres *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_readres_alloc ()
{
  return New uvfs_readres;
}
bool_t
xdr_uvfs_readres (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_readres *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_readres *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_writeres_alloc ()
{
  return New uvfs_writeres;
}
bool_t
xdr_uvfs_writeres (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_writeres *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_writeres *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_renameres_alloc ()
{
  return New uvfs_renameres;
}
bool_t
xdr_uvfs_renameres (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_renameres *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_renameres *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_linkres_alloc ()
{
  return New uvfs_linkres;
}
bool_t
xdr_uvfs_linkres (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_linkres *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_linkres *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_statfsres_alloc ()
{
  return New uvfs_statfsres;
}
bool_t
xdr_uvfs_statfsres (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_statfsres *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_statfsres *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_commitres_alloc ()
{
  return New uvfs_commitres;
}
bool_t
xdr_uvfs_commitres (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_commitres *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_commitres *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_filename_alloc ()
{
  return New uvfs_filename;
}
bool_t
xdr_uvfs_filename (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_filename *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_filename *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_pathname_alloc ()
{
  return New uvfs_pathname;
}
bool_t
xdr_uvfs_pathname (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_pathname *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_pathname *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_time_alloc ()
{
  return New uvfs_time;
}
bool_t
xdr_uvfs_time (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_time *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_time *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_sattr_alloc ()
{
  return New uvfs_sattr;
}
bool_t
xdr_uvfs_sattr (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_sattr *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_sattr *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_guard_alloc ()
{
  return New uvfs_guard;
}
bool_t
xdr_uvfs_guard (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_guard *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_guard *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfsstat_alloc ()
{
  return New uvfsstat;
}
bool_t
xdr_uvfsstat (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfsstat *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfsstat *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_readdirargs_alloc ()
{
  return New uvfs_readdirargs;
}
bool_t
xdr_uvfs_readdirargs (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_readdirargs *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_readdirargs *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_direntry_alloc ()
{
  return New uvfs_direntry;
}
bool_t
xdr_uvfs_direntry (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_direntry *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_direntry *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_dirlist_alloc ()
{
  return New uvfs_dirlist;
}
bool_t
xdr_uvfs_dirlist (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_dirlist *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_dirlist *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_readdirres_alloc ()
{
  return New uvfs_readdirres;
}
bool_t
xdr_uvfs_readdirres (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_readdirres *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_readdirres *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_setattrargs_alloc ()
{
  return New uvfs_setattrargs;
}
bool_t
xdr_uvfs_setattrargs (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_setattrargs *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_setattrargs *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
post_op_uvfs_fh_alloc ()
{
  return New post_op_uvfs_fh;
}
bool_t
xdr_post_op_uvfs_fh (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<post_op_uvfs_fh *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<post_op_uvfs_fh *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_diropargs_alloc ()
{
  return New uvfs_diropargs;
}
bool_t
xdr_uvfs_diropargs (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_diropargs *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_diropargs *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_diropresok_alloc ()
{
  return New uvfs_diropresok;
}
bool_t
xdr_uvfs_diropresok (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_diropresok *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_diropresok *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_diropres_alloc ()
{
  return New uvfs_diropres;
}
bool_t
xdr_uvfs_diropres (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_diropres *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_diropres *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_readargs_alloc ()
{
  return New uvfs_readargs;
}
bool_t
xdr_uvfs_readargs (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_readargs *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_readargs *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_writeargs_alloc ()
{
  return New uvfs_writeargs;
}
bool_t
xdr_uvfs_writeargs (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_writeargs *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_writeargs *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_createargs_alloc ()
{
  return New uvfs_createargs;
}
bool_t
xdr_uvfs_createargs (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_createargs *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_createargs *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_mkdirargs_alloc ()
{
  return New uvfs_mkdirargs;
}
bool_t
xdr_uvfs_mkdirargs (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_mkdirargs *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_mkdirargs *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_renameargs_alloc ()
{
  return New uvfs_renameargs;
}
bool_t
xdr_uvfs_renameargs (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_renameargs *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_renameargs *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_commitargs_alloc ()
{
  return New uvfs_commitargs;
}
bool_t
xdr_uvfs_commitargs (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_commitargs *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_commitargs *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_linkargs_alloc ()
{
  return New uvfs_linkargs;
}
bool_t
xdr_uvfs_linkargs (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_linkargs *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_linkargs *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_symlinkargs_alloc ()
{
  return New uvfs_symlinkargs;
}
bool_t
xdr_uvfs_symlinkargs (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_symlinkargs *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_symlinkargs *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_accessargs_alloc ()
{
  return New uvfs_accessargs;
}
bool_t
xdr_uvfs_accessargs (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_accessargs *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_accessargs *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_lookupresok_alloc ()
{
  return New uvfs_lookupresok;
}
bool_t
xdr_uvfs_lookupresok (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_lookupresok *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_lookupresok *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
uvfs_lookupres_alloc ()
{
  return New uvfs_lookupres;
}
bool_t
xdr_uvfs_lookupres (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_lookupres *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_lookupres *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

static const rpcgen_table uvfsprog_1_tbl[] = {
  UVFSPROG_1_APPLY (XDRTBL_DECL)
};
const rpc_program uvfsprog_1 = {
  UVFSPROG, UVFSVER, uvfsprog_1_tbl,
  sizeof (uvfsprog_1_tbl) / sizeof (uvfsprog_1_tbl[0]),
  "uvfsprog_1"
};

void *
uvfs_invalidateargs_alloc ()
{
  return New uvfs_invalidateargs;
}
bool_t
xdr_uvfs_invalidateargs (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<uvfs_invalidateargs *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<uvfs_invalidateargs *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

static const rpcgen_table uvfscbprog_1_tbl[] = {
  UVFSCBPROG_1_APPLY (XDRTBL_DECL)
};
const rpc_program uvfscbprog_1 = {
  UVFSCBPROG, UVFSCBVER, uvfscbprog_1_tbl,
  sizeof (uvfscbprog_1_tbl) / sizeof (uvfscbprog_1_tbl[0]),
  "uvfscbprog_1"
};


